### PR TITLE
Fix breakage after base unexported at-with

### PR DESCRIPTION
**Pull request by yuyichao**
Ref https://github.com/JuliaLang/julia/pull/53004

### CODE REVIEW

**Comment by palday** [comment]
Would be great to get this merged and released because it's leading to MixedModels.jl tests failing on 1.11 and nightly.

**Review by joachimbrand — APPROVED** [review]
Looks like the right fix. 
It would be good to have this merged soon as Rimu.jl is failing CI on nightly due to this issue.

**Comment by MilesCranmer** [comment]
Thanks; this was breaking some CI.

Also, why was that merged into JuliaLang? Doesn't seem to follow SemVer?

**Comment by MilesCranmer** [comment]
Shared some complaints here... https://github.com/JuliaLang/julia/pull/53004#issuecomment-2016674510. I feel like it's a bad precedent to set

**Comment by palday** [comment]
@MilesCranmer 1.11 isn't yet released and this only became available on 1.11, so now is the time to make such changes.

**Comment by MilesCranmer** [comment]
Ping, can this be merged?

**Comment by yuyichao** [comment]
Seems that https://github.com/JuliaIO/Suppressor.jl/pull/63 should fix the error for the latest version although as clarified in https://github.com/JuliaLang/julia/pull/53628 the correct fix should be to use `Base.ScopedValues` explicitly (as in this PR) rather than to use `Base.@with` explicitly.

**Pull request merged**
