### PR TITLE
 Use CompatHelper

### PR DESCRIPTION
**Pull request by aminya**

### CODE REVIEW

**Comment by ssfrr** [comment]
It would be good to continue testing on Julia v1.0.x.

Also can you describe the CompatHelper thing? I've heard it mentioned but don't really know how it works - from the config it looks like it runs as a cron job - on what machine? Does it need something set up in the Github repo to work? Is this related to GitHub actions?

**Comment by aminya** [comment]
> Also can you describe the CompatHelper thing? I've heard it mentioned but don't really know how it works - from the config it looks like it runs as a cron job - on what machine? Does it need something set up in the Github repo to work? Is this related to GitHub actions?

It will check Julia registry and will make pull requests to update the compat section or Project.toml once new packages are registered. 

Once merged it should show up in the Actions tab of the repo. Otherwise, follow https://github.com/bcbi/CompatHelper.jl#actions-setup

**Comment by ssfrr** [comment]
The version should be `1.0` (also on both travis and appveyor). Setting the version as `1` will use the latest `1.x.x` release.

CompatHelper seems pretty cool - thanks. So many robots.

**Comment by aminya** [comment]
Is there anything blocking this from merging?

**Comment by omus** [comment]
Can you resolve the conflicts? I imagine you'll only need the CompatHelper changes.

**Comment by aminya** [comment]
It's done

**Review by omus — APPROVED** [review]

**Pull request merged**
